baseURL = "https://dontmover.ru/"
languageCode = "ru-ru"
title = "Мой сайт на Hugo"
theme = "aafu"

[params]
  author = "Ваше имя"
  description = "Краткое описание сайта"
  [params.theme]
    mainTheme = "dark"  # "light", "dark" или null

[params.profile]
  name = "Имя Фамилия"
  tagline = "Краткий титул"
  location = "Город, Страна"
  photo = "images/profile.jpg"

showAttribute = true